# Generated by Django 2.2.12 on 2020-04-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customtext_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='tsrr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_tsrr', to='home.CustomText'),
        ),
    ]
