# Generated by Django 2.2.12 on 2020-04-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_test'),
        ('users', '0002_auto_20200409_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_test', to='home.CustomText'),
        ),
    ]
